[package]
name = "basm"
version = "0.1.0"
edition = "2021"

[dependencies]
compiler_builtins = { version = "0.1.84", features = ["mem"] }
dtoa = "1.0.8"
libm = "0.2.7"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
