name: Check hhdr-rs

on:
  - push

env:
  CARGO_NET_RETRY: 10
  CI: 1
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          components: clippy
      - name: Install System packages
        run: |
          sudo apt update
          sudo apt install nasm
      - name: Clippy
        run: cargo clippy
        env:
          RUSTFLAGS: "-D warnings"
      - name: Test
        run: cargo test
      - name: Check C
        run: |
          scripts/check.sh \
            "./release.sh | tee /tmp/code.c" \
            "cc -w /tmp/code.c -o /tmp/bin"
      - name: Check C (no-probe)
        run: |
          scripts/check.sh \
            "./release.sh --features no-probe | tee /tmp/code.c" \
            "cc -w /tmp/code.c -o /tmp/bin"
      - name: Check ASM
        run: |
          scripts/check.sh \
            "./release-asm.sh | tee /tmp/code.s" \
            "nasm -f elf64 /tmp/code.s -o /tmp/code.o && cc /tmp/code.o -o /tmp/bin"
      - name: Check ASM (no-probe)
        run: |
          scripts/check.sh \
            "./release-asm.sh --features no-probe | tee /tmp/code.s" \
            "nasm -f elf64 /tmp/code.s -o /tmp/code.o && cc /tmp/code.o -o /tmp/bin"
      - name: Check Rust
        run: |
          scripts/check.sh \
            "./release-rs.sh | tee /tmp/code.rs" \
            "rustc +stable -O -A dead-code /tmp/code.rs -o /tmp/bin"
      - name: Check Rust (no-probe)
        run: |
          scripts/check.sh \
            "./release-rs.sh --features no-probe | tee /tmp/code.rs" \
            "rustc +stable -O -A dead-code /tmp/code.rs -o /tmp/bin"
