name: Check

on:
  - push
  - pull_request

env:
  CARGO_NET_RETRY: 10
  CI: 1
  RUSTUP_MAX_RETRIES: 10

jobs:
  build:
    name: CI (macOS)
    runs-on: macos-14
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - wasm32-unknown-unknown
    env:
      CARGO_BUILD_TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          rustup toolchain install nightly --target ${{ matrix.target }} --profile default --component clippy
      - name: Install Python 3      
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install System packages
        run: |
          brew update
          brew upgrade
          brew install gcc
          rustup component add rust-src --toolchain nightly-aarch64-apple-darwin
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings -A clippy::missing_safety_doc
      - name: Rustfmt
        run: cargo fmt --check --all
      - name: Test
        if: ${{ matrix.target != 'wasm32-unknown-unknown' }}
        run: cargo test --lib -- --test-threads 1
      - name: Check cargo build
        if: ${{ matrix.target != 'wasm32-unknown-unknown' }}
        run: |
          python3 ./scripts/ci.py ${{ runner.temp }} _ CargoDev 0 ./tests/ci.json
      - name: Check cargo build --release
        if: ${{ matrix.target != 'wasm32-unknown-unknown' }}
        run: |
          python3 ./scripts/ci.py ${{ runner.temp }} _ CargoRelease 0 ./tests/ci.json
      - name: Check wasm32
        if: ${{ matrix.target == 'wasm32-unknown-unknown' }}
        run: |
          python3 ./scripts/ci.py ${{ runner.temp }} ./release-wasm32.sh JavaScript 32 ./tests/ci.json